### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [sjlawton/proj6#1]
I see a couple issues. First, it looks like this [isn't quite valid HTML](http://validator.w3.org/check?uri=https%3A%2F%2Fboiling-shore-4085.herokuapp.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0). Could you fix the errors and update?

Second, there's some pretty inconsistent indentation. In Ruby (`.rb`) files, we should always use two-space soft-tabs. See the paragraph below for how to fix that. In other files, I don't mind which kind of indentation you use, but it should be consistently hard-tabs or consistently soft-tabs per file type.

The standard indentation for Ruby (`.rb`) files is actually with two-space soft-tabs rather than hard-tabs. See if you can update your text editor to use two-space soft-tabs for all Ruby files. If you have trouble figuring it out, [this page may be helpful](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md). If it's not, just let me know and I'll be happy to point you in the right direction.

When both of these issues are fixed, just ping me here and I'll take another look.

**Comment by sjlawton** [comment]
Both should be fixed now.

**Comment by chrisvfritz** [comment]
The HTML looks better, but if you check out the [`app.rb`](https://github.com/sjlawton/proj6/blob/master/app.rb) and [`index.erb`](https://github.com/sjlawton/proj6/blob/master/views/index.erb) files on GitHub, the mix of hard-tabs and soft-tabs is still causing some indentation issues. If you're using Sublime Text, [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) should probably help you resolve that. If you're using another editor, let me know and we'll figure out which settings are appropriate for that program.

**Comment by chrisvfritz** [comment]
Your `app.rb` is looking quite a bit better now, but I still see some inconsistent indentation in [`index.erb`](https://github.com/sjlawton/proj6/blob/master/views/index.erb). Let me know if you encounter any problems fixing it and I'll be happy to hop on a screenshare for some joint troubleshooting.

**Comment by sjlawton** [comment]
Sorry, should be fixed now.

**Comment by chrisvfritz** [comment]
:+1: Fantastic!
